version: '3.4'
services:
  cassis:
    build: .
    container_name: nuxt-cassis
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - '3000:3000'

  mongodb:
    image: mongo:latest
    container_name: nuxt-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
