version: '3.4'
services:
  cassis:
    build: .
    container_name: nuxt-cassis
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    networks:
      - cassis-mongo
      - cassis

  mongodb:
    image: mongo:latest
    container_name: nuxt-mongo
    ports:
      - '27017:27017'
    networks:
      - cassis-mongo
    volumes:
      - mongodbdata:/data/db

networks:
  cassis-mongo:
    driver: bridge

  cassis:
    external:
      name: eirb_connect

volumes:
  mongodbdata:
    driver: local
